"""Durable account-bound working artifacts generated by JANUS.

Artifacts are explicit exports/reports, not hidden scratchpads. They are assembled
from auditable persisted state (continuity, research, synthesis or supplied note),
stored through the existing authenticated JANUS file subsystem, indexed for later
document grounding, and linked to their source provenance.
"""
from __future__ import annotations

import json
import os
import re
import sqlite3
import time
from datetime import datetime, timezone
from typing import Any, Optional

from fastapi import APIRouter, Header, HTTPException
from pydantic import BaseModel

import auth
import attachment_api
import continuity_ledger

router = APIRouter(prefix="/artifacts", tags=["artifacts"])
DB_PATH = os.getenv("JANUS_DB_PATH", "/data/janus.sqlite3")
KINDS = {"continuity_report", "project_snapshot", "research_digest", "working_note"}


class ArtifactRequest(BaseModel):
    kind: str
    title: str = ""
    continuity_item_id: Optional[int] = None
    note: str = ""
    research_limit: int = 8


def _db() -> sqlite3.Connection:
    c = sqlite3.connect(DB_PATH, timeout=10)
    c.row_factory = sqlite3.Row
    c.execute("PRAGMA journal_mode=WAL")
    c.executescript("""
    CREATE TABLE IF NOT EXISTS janus_outbound_artifacts(
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      account_id INTEGER NOT NULL,
      profile_id TEXT NOT NULL,
      file_id TEXT NOT NULL,
      kind TEXT NOT NULL,
      title TEXT NOT NULL,
      continuity_item_id INTEGER,
      provenance_json TEXT NOT NULL DEFAULT '{}',
      created_at INTEGER NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_outbound_artifacts_account_time
      ON janus_outbound_artifacts(account_id,created_at DESC);
    CREATE UNIQUE INDEX IF NOT EXISTS idx_outbound_artifacts_file
      ON janus_outbound_artifacts(file_id);
    """)
    return c


def _now_text() -> str:
    return datetime.now(timezone.utc).isoformat()


def _safe_slug(value: str) -> str:
    x = re.sub(r"[^A-Za-z0-9._-]+", "-", str(value or "").strip()).strip("-._")
    return (x[:80] or "janus-artifact").lower()


def _account(authorization: Optional[str]):
    return auth.require_account(authorization)


def _profile(account) -> str:
    return str(account["username"])


def _header(title: str, kind: str, profile: str) -> list[str]:
    return [
        f"# {title}",
        "",
        f"Generated by JANUS: {_now_text()}",
        f"Artifact type: {kind}",
        f"Profile: {profile}",
        "",
        "> This is an externalized working artifact assembled from persisted JANUS records. It is not private chain-of-thought. Historical, provisional and unresolved material remains labelled as such.",
        "",
    ]


def _continuity_report(profile: str, title: str) -> tuple[str, dict[str, Any]]:
    items = continuity_ledger.list_items(profile, open_only=False, limit=150)
    lines = _header(title, "continuity_report", profile)
    open_items = [x for x in items if x.get("state") in continuity_ledger.OPEN_STATES]
    closed = [x for x in items if x.get("state") not in continuity_ledger.OPEN_STATES]
    lines += ["## Current / open work", ""]
    if not open_items:
        lines.append("No open continuity items are currently recorded.")
    for x in open_items:
        lines += [f"### #{x['id']} — {x['title']}", f"- Type: {x['kind']}", f"- State: {x['state']}", f"- Priority: {x['priority']}"]
        if x.get("detail"): lines.append(f"- Detail: {x['detail']}")
        lines.append("")
    lines += ["## Historical / closed / deferred work", ""]
    for x in closed[:80]:
        lines.append(f"- #{x['id']} [{x['kind']}:{x['state']}] {x['title']}")
    return "\n".join(lines).strip()+"\n", {"continuity_item_ids": [int(x["id"]) for x in items]}


def _project_snapshot(profile: str, item_id: int, title: str) -> tuple[str, dict[str, Any]]:
    try:
        item = continuity_ledger.get_item(profile, int(item_id))
    except KeyError:
        raise HTTPException(404, "Tracked continuity item not found")
    events = continuity_ledger.events(profile, int(item_id), limit=120)
    lines = _header(title, "project_snapshot", profile)
    lines += [
        "## Tracked item", "",
        f"- ID: #{item['id']}", f"- Type: {item['kind']}", f"- State: {item['state']}",
        f"- Priority: {item['priority']}", f"- Title: {item['title']}",
    ]
    if item.get("detail"): lines.append(f"- Detail: {item['detail']}")
    if item.get("tags"): lines.append("- Tags: " + ", ".join(item["tags"]))
    lines += ["", "## Lifecycle history", ""]
    for ev in reversed(events):
        transition = ""
        if ev.get("old_state") or ev.get("new_state"):
            transition = f" ({ev.get('old_state') or '—'} → {ev.get('new_state') or '—'})"
        note = str(ev.get("note") or "").strip()
        lines.append(f"- {ev.get('created_at')} — {ev.get('event_type')}{transition}" + (f": {note}" if note else ""))
    return "\n".join(lines).strip()+"\n", {"continuity_item_id": int(item_id), "event_count": len(events)}


def _research_rows(profile: str, limit: int) -> list[dict[str, Any]]:
    try:
        with _db() as c:
            rows = c.execute(
                "SELECT id,core_name,mode,query,result,sources_json,completed_at FROM janus_curiosity_searches WHERE profile_id=? AND status='complete' ORDER BY id DESC LIMIT ?",
                (profile, max(1, min(30, int(limit)))),
            ).fetchall()
        return [dict(r) for r in rows]
    except Exception:
        return []


def _synthesis_rows(profile: str, limit: int = 8) -> list[dict[str, Any]]:
    try:
        with _db() as c:
            rows = c.execute(
                "SELECT id,left_search_id,right_search_id,status,result,reason,completed_at FROM janus_background_synthesis WHERE profile_id=? ORDER BY id DESC LIMIT ?",
                (profile, int(limit)),
            ).fetchall()
        return [dict(r) for r in rows]
    except Exception:
        return []


def _research_digest(profile: str, title: str, limit: int) -> tuple[str, dict[str, Any]]:
    rows = _research_rows(profile, limit)
    synth = _synthesis_rows(profile)
    lines = _header(title, "research_digest", profile)
    lines += ["## Recent completed research", ""]
    if not rows:
        lines.append("No completed curiosity/web research records were available for this profile.")
    for r in rows:
        lines += [f"### Research #{r['id']}: {r.get('query') or 'Untitled query'}", f"- Mode: {r.get('mode') or 'unknown'}", f"- Core: {r.get('core_name') or 'unknown'}", f"- Completed: {r.get('completed_at') or 'unknown'}", "", str(r.get("result") or "").strip(), ""]
        try:
            sources = json.loads(str(r.get("sources_json") or "[]"))
        except Exception:
            sources = []
        if sources:
            lines.append("Sources recorded by retrieval:")
            for s in sources[:12]:
                if isinstance(s, dict):
                    label = str(s.get("title") or s.get("url") or "source")
                    url = str(s.get("url") or "")
                    lines.append(f"- {label}" + (f" — {url}" if url else ""))
                else:
                    lines.append(f"- {s}")
            lines.append("")
    lines += ["## Cross-research synthesis records", ""]
    for s in synth:
        lines.append(f"### Synthesis #{s['id']} [{s.get('status')}] — research {s.get('left_search_id')} + {s.get('right_search_id')}")
        if s.get("result"): lines.append(str(s["result"]).strip())
        if s.get("reason"): lines.append(f"Reason/status note: {s['reason']}")
        lines.append("")
    return "\n".join(lines).strip()+"\n", {"research_ids": [int(r["id"]) for r in rows], "synthesis_ids": [int(s["id"]) for s in synth]}


def _working_note(profile: str, title: str, note: str) -> tuple[str, dict[str, Any]]:
    text = str(note or "").strip()
    if not text:
        raise HTTPException(400, "A working_note artifact requires note text")
    lines = _header(title, "working_note", profile) + ["## Note", "", text]
    return "\n".join(lines).strip()+"\n", {"source": "explicit_note"}


def create_artifact(account, req: ArtifactRequest) -> dict[str, Any]:
    kind = str(req.kind or "").strip().lower()
    if kind not in KINDS:
        raise HTTPException(400, f"Unsupported artifact kind: {kind}")
    profile = _profile(account)
    default_titles = {
        "continuity_report": "JANUS Continuity Report",
        "project_snapshot": "JANUS Project Snapshot",
        "research_digest": "JANUS Research Digest",
        "working_note": "JANUS Working Note",
    }
    title = " ".join((req.title or default_titles[kind]).split())[:160]
    if kind == "continuity_report":
        content, provenance = _continuity_report(profile, title)
    elif kind == "project_snapshot":
        if req.continuity_item_id is None:
            raise HTTPException(400, "project_snapshot requires continuity_item_id")
        content, provenance = _project_snapshot(profile, int(req.continuity_item_id), title)
    elif kind == "research_digest":
        content, provenance = _research_digest(profile, title, req.research_limit)
    else:
        content, provenance = _working_note(profile, title, req.note)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    filename = f"{_safe_slug(title)}-{stamp}.md"
    file_meta = attachment_api.store_generated_file(int(account["id"]), filename, content.encode("utf-8"), "text/markdown")
    with _db() as c:
        cur = c.execute(
            "INSERT INTO janus_outbound_artifacts(account_id,profile_id,file_id,kind,title,continuity_item_id,provenance_json,created_at) VALUES(?,?,?,?,?,?,?,?)",
            (int(account["id"]), profile, file_meta["id"], kind, title, req.continuity_item_id, json.dumps(provenance, ensure_ascii=False), int(time.time())),
        )
        artifact_id = int(cur.lastrowid)
    return {"id": artifact_id, "kind": kind, "title": title, "profile": profile, "file": file_meta, "provenance": provenance}


@router.post("")
def artifact_create(req: ArtifactRequest, authorization: Optional[str] = Header(default=None)):
    account = _account(authorization)
    return {"ok": True, "artifact": create_artifact(account, req)}


@router.get("")
def artifact_list(authorization: Optional[str] = Header(default=None)):
    account = _account(authorization)
    with _db() as c:
        rows = c.execute(
            """SELECT a.*,f.original_name,f.mime_type,f.size_bytes,f.created_at file_created_at
               FROM janus_outbound_artifacts a
               LEFT JOIN janus_files f ON f.id=a.file_id AND f.account_id=a.account_id
               WHERE a.account_id=? ORDER BY a.id DESC LIMIT 200""",
            (int(account["id"]),),
        ).fetchall()
    items = []
    for r in rows:
        d = dict(r)
        try: d["provenance"] = json.loads(d.pop("provenance_json") or "{}")
        except Exception: d["provenance"] = {}
        d["available"] = bool(d.get("original_name"))
        d["download_path"] = f"/files/{d['file_id']}/download" if d["available"] else None
        items.append(d)
    return {"ok": True, "items": items}


@router.get("/{artifact_id}")
def artifact_info(artifact_id: int, authorization: Optional[str] = Header(default=None)):
    account = _account(authorization)
    with _db() as c:
        r = c.execute(
            """SELECT a.*,f.original_name,f.mime_type,f.size_bytes FROM janus_outbound_artifacts a
               LEFT JOIN janus_files f ON f.id=a.file_id AND f.account_id=a.account_id
               WHERE a.id=? AND a.account_id=?""",
            (int(artifact_id), int(account["id"])),
        ).fetchone()
    if not r:
        raise HTTPException(404, "Artifact not found")
    d = dict(r)
    try: d["provenance"] = json.loads(d.pop("provenance_json") or "{}")
    except Exception: d["provenance"] = {}
    d["available"] = bool(d.get("original_name"))
    d["download_path"] = f"/files/{d['file_id']}/download" if d["available"] else None
    return {"ok": True, "artifact": d}
