package com.vardath.janus;

import android.app.Activity;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.util.Base64;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;

import org.json.JSONObject;

import java.util.Collections;
import java.util.Set;
import java.util.WeakHashMap;

/** Restores generated-image cards from structured Chat metadata, including after process restart. */
public final class JanusGeneratedImagePolish {
    private static final Set<Activity> INSTALLED = Collections.newSetFromMap(new WeakHashMap<>());
    private static final String TAG_PREFIX = "janus-generated-image:";
    private JanusGeneratedImagePolish() {}

    public static void install(Activity activity) {
        if (activity == null || INSTALLED.contains(activity)) return;
        INSTALLED.add(activity);
        activity.getWindow().getDecorView().getViewTreeObserver().addOnGlobalLayoutListener(() -> {
            View root = activity.findViewById(android.R.id.content);
            if (root != null) walk(activity, root);
        });
    }

    private static void walk(Activity activity, View view) {
        if (view instanceof LinearLayout) enhance(activity, (LinearLayout) view);
        if (view instanceof ViewGroup) {
            ViewGroup g = (ViewGroup) view;
            for (int i = 0; i < g.getChildCount(); i++) walk(activity, g.getChildAt(i));
        }
    }

    private static void enhance(Activity activity, LinearLayout card) {
        if (card.getChildCount() < 2) return;
        if (!(card.getChildAt(0) instanceof TextView) || !(card.getChildAt(1) instanceof TextView)) return;
        if (!"JANUS".contentEquals(((TextView) card.getChildAt(0)).getText())) return;
        TextView body = (TextView) card.getChildAt(1);
        JanusChatPresentation p = JanusChatResponseRegistry.findForReply(String.valueOf(body.getText()));
        if (p == null || p.generatedImage == null) return;
        String fileId = p.generatedImage.optString("file_id", "").trim();
        if (fileId.isEmpty()) return;
        String tag = TAG_PREFIX + fileId;
        if (card.findViewWithTag(tag) != null) return;

        TextView loading = new TextView(activity);
        loading.setText("Generated image · loading…");
        loading.setTextSize(12);
        loading.setTag(tag);
        card.addView(loading, new LinearLayout.LayoutParams(-1, -2));

        new Thread(() -> {
            try {
                JanusApiClient api = new JanusApiClient(activity);
                JanusApiClient.Response r = api.get("/images/" + java.net.URLEncoder.encode(fileId, java.nio.charset.StandardCharsets.UTF_8) + "/inline", true);
                if (!r.ok()) throw new IllegalStateException("HTTP " + r.code);
                JSONObject j = new JSONObject(r.body);
                byte[] bytes = Base64.decode(j.optString("data_base64", ""), Base64.DEFAULT);
                Bitmap bitmap = BitmapFactory.decodeByteArray(bytes, 0, bytes.length);
                if (bitmap == null) throw new IllegalStateException("Image unavailable");
                activity.runOnUiThread(() -> {
                    int index = card.indexOfChild(loading);
                    if (index < 0) return;
                    card.removeView(loading);
                    ImageView image = new ImageView(activity);
                    image.setTag(tag);
                    image.setAdjustViewBounds(true);
                    image.setContentDescription("Image generated by JANUS");
                    image.setImageBitmap(bitmap);
                    LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(-1, -2);
                    lp.setMargins(0, dp(activity, 8), 0, dp(activity, 6));
                    card.addView(image, Math.min(index, card.getChildCount()), lp);
                });
            } catch (Exception e) {
                activity.runOnUiThread(() -> loading.setText("Generated image · unavailable"));
            }
        }, "janus-image-restore").start();
    }

    private static int dp(Activity activity, int value) {
        return Math.round(value * activity.getResources().getDisplayMetrics().density);
    }
}
