package com.vardath.janus.v080;

import android.content.Context;
import android.content.Intent;
import android.database.Cursor;
import android.graphics.Typeface;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.provider.OpenableColumns;
import android.text.method.ScrollingMovementMethod;
import android.util.Base64;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URLEncoder;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public final class MainActivity extends AppCompatActivity {
    private static final String PREFS="janus_v080", TOKEN="access_token", PROFILE="profile", QUEUE="chat_queue";
    private static final int PICK_FILE=4080, MAX_ATTACHMENTS=4, MAX_FILE_BYTES=8*1024*1024;
    private static final long[] RETRY={8000L,25000L,60000L};
    private final ExecutorService io=Executors.newSingleThreadExecutor();
    private final Handler ui=new Handler(Looper.getMainLooper());
    private final Set<String> rendered=new HashSet<>(), inFlight=new HashSet<>();
    private final List<Attachment> draftAttachments=new ArrayList<>();
    private LinearLayout root,content,attachmentRow; private TextView status,chat,attachmentStatus; private ScrollView chatScroll;
    private String accessToken="", profile="", activeTab="Chat";

    @Override protected void onCreate(@Nullable Bundle state){super.onCreate(state); accessToken=prefs().getString(TOKEN,""); profile=prefs().getString(PROFILE,""); buildRoot(); if(accessToken.isBlank())showAuth();else validateSession();}
    @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
    @Override protected void onActivityResult(int requestCode,int resultCode,@Nullable Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==PICK_FILE&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null)uploadPickedFile(data.getData());}
    private android.content.SharedPreferences prefs(){return getSharedPreferences(PREFS,Context.MODE_PRIVATE);}
    private void buildRoot(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(18),dp(16),dp(14));root.addView(text("JANUS · v0.80 dev · 11 cores · 7→2→1→1",18,true),mw());status=text("Starting…",13,false);status.setPadding(0,dp(6),0,dp(10));root.addView(status,mw());content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}

    private void showAuth(){content.removeAllViews();activeTab="Auth";status.setText("Not signed in · checking server…");checkHealth();content.addView(text("Sign in to JANUS",30,true),mw());EditText id=input("Username or email"),email=input("Email (for registration)"),pw=input("Password");pw.setInputType(0x81);content.addView(id,mw());content.addView(email,mw());content.addView(pw,mw());Button login=button("Sign in"),register=button("Create account");content.addView(login,mw());content.addView(register,mw());content.addView(text("Clean native v0.80 rebuild · installed alongside legacy JANUS during validation.",14,false),mw());login.setOnClickListener(v->{if(id.getText().toString().trim().isEmpty()||pw.getText().toString().isEmpty()){toast("Enter username/email and password.");return;}JSONObject b=new JSONObject();try{b.put("identifier",id.getText().toString().trim());b.put("password",pw.getText().toString());}catch(Exception ignored){}authenticate("/auth/login",b);});register.setOnClickListener(v->{if(id.getText().toString().trim().isEmpty()||email.getText().toString().trim().isEmpty()||pw.getText().toString().isEmpty()){toast("Registration needs username, email and password.");return;}JSONObject b=new JSONObject();try{b.put("username",id.getText().toString().trim());b.put("email",email.getText().toString().trim());b.put("password",pw.getText().toString());}catch(Exception ignored){}authenticate("/auth/register",b);});}
    private void authenticate(String path,JSONObject body){status.setText("Connecting to JANUS…");io.execute(()->{HttpResult r=request("POST",path,body.toString(),false);if(r.ok()){try{JSONObject j=new JSONObject(r.body);String t=j.optString("access_token","");String p=j.optJSONObject("account")!=null?j.optJSONObject("account").optString("username",""):"";if(!t.isBlank()){saveSession(t,p);ui.post(this::showApp);return;}}catch(Exception ignored){}}ui.post(()->status.setText("Sign-in failed · "+friendly(r)));});}
    private void validateSession(){status.setText("Restoring JANUS session…");io.execute(()->{HttpResult r=request("GET","/auth/me",null,true);ui.post(()->{if(r.ok()){try{JSONObject a=new JSONObject(r.body).optJSONObject("account");if(a!=null){profile=a.optString("username",profile);prefs().edit().putString(PROFILE,profile).apply();}}catch(Exception ignored){}showApp();}else{clearSession();showAuth();status.setText("Session expired or unavailable · sign in again");}});});}
    private void saveSession(String token,String p){accessToken=token;profile=p;prefs().edit().putString(TOKEN,token).putString(PROFILE,p).apply();}
    private void clearSession(){accessToken="";profile="";draftAttachments.clear();prefs().edit().remove(TOKEN).remove(PROFILE).apply();}

    private void showApp(){content.removeAllViews();LinearLayout tabs=new LinearLayout(this);tabs.setOrientation(LinearLayout.HORIZONTAL);for(String n:new String[]{"Chat","Messages","Observe","Options"}){Button b=button(n);b.setOnClickListener(v->showTab(n));tabs.addView(b,new LinearLayout.LayoutParams(0,-2,1));}content.addView(tabs,mw());LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setTag("page");content.addView(page,new LinearLayout.LayoutParams(-1,0,1));status.setText("Connected · checking compatibility…");checkCapabilities();showTab("Chat");flushSoon(500);}
    private LinearLayout page(){for(int i=0;i<content.getChildCount();i++){View v=content.getChildAt(i);if(v instanceof LinearLayout&&"page".equals(v.getTag()))return(LinearLayout)v;}throw new IllegalStateException("page missing");}
    private void showTab(String tab){activeTab=tab;LinearLayout p=page();p.removeAllViews();if(tab.equals("Messages"))showMessages(p);else if(tab.equals("Observe"))showObserve(p);else if(tab.equals("Options"))showOptions(p);else showChat(p);}

    private void showChat(LinearLayout p){p.addView(text("Chat",30,true),mw());chat=text("JANUS v0.80 Stage 4 · resilient Chat + native grounded attachments.\n",16,false);chat.setMovementMethod(new ScrollingMovementMethod());chatScroll=new ScrollView(this);chatScroll.addView(chat,mw());p.addView(chatScroll,new LinearLayout.LayoutParams(-1,0,1));renderQueued();
        LinearLayout attachmentControls=new LinearLayout(this);attachmentControls.setOrientation(LinearLayout.HORIZONTAL);Button attach=button("Attach file");attachmentStatus=text("0 / "+MAX_ATTACHMENTS+" attached",13,false);attachmentControls.addView(attach,ww());attachmentControls.addView(attachmentStatus,new LinearLayout.LayoutParams(0,-2,1));p.addView(attachmentControls,mw());
        attachmentRow=new LinearLayout(this);attachmentRow.setOrientation(LinearLayout.HORIZONTAL);HorizontalScrollView attachmentScroll=new HorizontalScrollView(this);attachmentScroll.addView(attachmentRow,mw());p.addView(attachmentScroll,mw());renderAttachmentChips();attach.setOnClickListener(v->pickFile());
        LinearLayout composer=new LinearLayout(this);composer.setOrientation(LinearLayout.HORIZONTAL);composer.setGravity(Gravity.CENTER_VERTICAL);EditText msg=input("Message JANUS");Button send=button("Send");composer.addView(msg,new LinearLayout.LayoutParams(0,-2,1));composer.addView(send,ww());p.addView(composer,mw());send.setOnClickListener(v->{String body=msg.getText().toString().trim();if(body.isEmpty()&&draftAttachments.isEmpty())return;if(body.isEmpty())body="Please assess the attached file or files.";msg.setText("");List<Attachment> files=new ArrayList<>(draftAttachments);draftAttachments.clear();renderAttachmentChips();enqueue(body,files);});}
    private void pickFile(){if(draftAttachments.size()>=MAX_ATTACHMENTS){toast("At most "+MAX_ATTACHMENTS+" attachments per Chat turn.");return;}Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,PICK_FILE);}
    private void uploadPickedFile(Uri uri){if(draftAttachments.size()>=MAX_ATTACHMENTS){toast("Attachment limit reached.");return;}String name=fileName(uri);String mime=getContentResolver().getType(uri);if(mime==null||mime.isBlank())mime="application/octet-stream";String finalMime=mime;status.setText("Uploading "+name+"…");io.execute(()->{try{byte[] bytes=readBytes(uri,MAX_FILE_BYTES);JSONObject b=new JSONObject();b.put("filename",name);b.put("mime_type",finalMime);b.put("data_base64",Base64.encodeToString(bytes,Base64.NO_WRAP));HttpResult r=request("POST","/files/upload",b.toString(),true);if(!r.ok()){ui.post(()->status.setText("Attachment upload failed · "+friendly(r)));return;}JSONObject file=new JSONObject(r.body).optJSONObject("file");if(file==null||file.optString("id","").isBlank()){ui.post(()->status.setText("Attachment upload failed · invalid server response"));return;}Attachment a=new Attachment(file.optString("id"),file.optString("filename",name),file.optString("mime_type",finalMime),file.optLong("size_bytes",bytes.length),file.optString("extraction_status","unknown"));ui.post(()->{if(draftAttachments.size()<MAX_ATTACHMENTS){draftAttachments.add(a);renderAttachmentChips();status.setText("Attachment ready · "+a.name);}else status.setText("Attachment uploaded but turn limit already reached");});}catch(FileTooLarge e){ui.post(()->status.setText("Attachment too large · maximum 8 MB"));}catch(Exception e){ui.post(()->status.setText("Attachment upload failed · "+e.getClass().getSimpleName()+": "+e.getMessage()));}});}
    private byte[] readBytes(Uri uri,int max)throws Exception{try(InputStream in=getContentResolver().openInputStream(uri);ByteArrayOutputStream out=new ByteArrayOutputStream()){if(in==null)throw new IllegalStateException("Unable to open selected file");byte[] buf=new byte[32768];int n,total=0;while((n=in.read(buf))!=-1){total+=n;if(total>max)throw new FileTooLarge();out.write(buf,0,n);}if(total==0)throw new IllegalArgumentException("Empty files are not supported");return out.toByteArray();}}
    private String fileName(Uri uri){String name="attachment";try(Cursor c=getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst()){String v=c.getString(0);if(v!=null&&!v.isBlank())name=v;}}catch(Exception ignored){}return name;}
    private void renderAttachmentChips(){if(attachmentStatus!=null)attachmentStatus.setText(draftAttachments.size()+" / "+MAX_ATTACHMENTS+" attached");if(attachmentRow==null)return;attachmentRow.removeAllViews();for(Attachment a:new ArrayList<>(draftAttachments)){Button chip=button("× "+a.name);chip.setOnClickListener(v->{draftAttachments.removeIf(x->x.id.equals(a.id));renderAttachmentChips();});attachmentRow.addView(chip,ww());}}

    private void enqueue(String message,List<Attachment> attachments){List<Q> q=loadQueue();long now=System.currentTimeMillis();String signature=attachmentSignature(attachments);for(Q x:q)if(x.message.equals(message)&&x.attachmentSignature().equals(signature)&&now-x.created<120000){status.setText("Already queued · duplicate suppressed");return;}Q x=new Q(UUID.randomUUID().toString(),message,0,now,attachments);q.add(x);saveQueue(q);renderOnce(x);status.setText("Sending to JANUS…");sendQueued(x.id);}
    private void sendQueued(String id){if(inFlight.contains(id))return;Q x=find(id);if(x==null)return;inFlight.add(id);io.execute(()->{JSONObject b=new JSONObject();try{b.put("message",x.message);b.put("client_message_id",x.id);JSONArray ids=new JSONArray();for(Attachment a:x.attachments)ids.put(a.id);b.put("attachment_ids",ids);}catch(Exception ignored){}HttpResult r=request("POST","/desktop/chat",b.toString(),true);inFlight.remove(id);if(r.ok()){String reply;try{JSONObject j=new JSONObject(r.body);reply=j.optString("reply",r.body);JSONArray grounded=j.optJSONArray("attachments");if(grounded!=null&&grounded.length()>0)reply+="\n\nGrounded attachments: "+grounded.length();}catch(Exception e){reply=r.body;}remove(id);String f=reply;ui.post(()->{if(chat!=null&&activeTab.equals("Chat")){chat.append("\nJANUS\n"+f+"\n");chatScroll.post(()->chatScroll.fullScroll(View.FOCUS_DOWN));}status.setText("Interface active");});return;}int a=increment(id);ui.post(()->status.setText("Queued locally · retry "+Math.min(a,RETRY.length)+"/"+RETRY.length+" · "+friendly(r)));if(a<=RETRY.length)flushSoon(RETRY[a-1]);});}
    private void flushSoon(long ms){ui.postDelayed(()->{if(accessToken.isBlank())return;for(Q x:loadQueue())if(x.attempts<=RETRY.length)sendQueued(x.id);},ms);}
    private void renderQueued(){for(Q x:loadQueue())renderOnce(x);} private void renderOnce(Q x){if(chat==null||!activeTab.equals("Chat")||rendered.contains(x.id))return;rendered.add(x.id);chat.append("\nYou\n"+x.message+(x.attachments.isEmpty()?"":"\nAttachments: "+attachmentNames(x.attachments))+"\nQueued locally\n");}
    private List<Q> loadQueue(){List<Q> out=new ArrayList<>();try{JSONArray a=new JSONArray(prefs().getString(QUEUE,"[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);List<Attachment> files=new ArrayList<>();JSONArray fa=o.optJSONArray("attachments");if(fa!=null)for(int k=0;k<fa.length();k++){JSONObject f=fa.getJSONObject(k);files.add(new Attachment(f.optString("id"),f.optString("name"),f.optString("mime"),f.optLong("size"),f.optString("extraction")));}out.add(new Q(o.optString("id"),o.optString("message"),o.optInt("attempts"),o.optLong("created_at"),files));}}catch(Exception ignored){}return out;}
    private void saveQueue(List<Q> q){JSONArray a=new JSONArray();try{for(Q x:q){JSONObject o=new JSONObject();o.put("id",x.id);o.put("message",x.message);o.put("attempts",x.attempts);o.put("created_at",x.created);JSONArray files=new JSONArray();for(Attachment f:x.attachments){JSONObject fo=new JSONObject();fo.put("id",f.id);fo.put("name",f.name);fo.put("mime",f.mime);fo.put("size",f.size);fo.put("extraction",f.extraction);files.put(fo);}o.put("attachments",files);a.put(o);}}catch(Exception ignored){}prefs().edit().putString(QUEUE,a.toString()).apply();}
    private Q find(String id){for(Q x:loadQueue())if(x.id.equals(id))return x;return null;} private int increment(String id){List<Q> q=loadQueue();int n=0;for(int i=0;i<q.size();i++){Q x=q.get(i);if(x.id.equals(id)){n=x.attempts+1;q.set(i,new Q(x.id,x.message,n,x.created,x.attachments));break;}}saveQueue(q);return n;} private void remove(String id){List<Q>q=loadQueue();q.removeIf(x->x.id.equals(id));saveQueue(q);}
    private String attachmentSignature(List<Attachment> a){StringBuilder b=new StringBuilder();for(Attachment x:a)b.append(x.id).append('|');return b.toString();} private String attachmentNames(List<Attachment>a){StringBuilder b=new StringBuilder();for(int i=0;i<a.size();i++){if(i>0)b.append(", ");b.append(a.get(i).name);}return b.toString();}

    private void showMessages(LinearLayout p){p.addView(text("Messages",30,true),mw());TextView remote=text("Loading JANUS outbox…",15,false);p.addView(remote,new LinearLayout.LayoutParams(-1,0,1));Button refresh=button("Refresh messages");p.addView(refresh,mw());refresh.setOnClickListener(v->loadMessages(remote));loadMessages(remote);}
    private void loadMessages(TextView view){if(profile.isBlank()){view.setText("Profile unavailable · restore your session first.");return;}io.execute(()->{String path="/desktop/messages?username="+enc(profile)+"&limit=50";HttpResult r=request("GET",path,null,true);String display;if(r.ok()){StringBuilder b=new StringBuilder();try{JSONObject j=new JSONObject(r.body);JSONArray items=j.optJSONArray("items");int unread=j.optInt("unread",0);b.append(unread).append(" unread\n\n");if(items!=null)for(int i=0;i<items.length();i++){JSONObject x=items.getJSONObject(i);b.append(x.optString("message_type","Message")).append(" · ").append(x.optString("state","unread")).append("\n").append(x.optString("detail","")).append("\n\n");}if(items==null||items.length()==0)b.append("No JANUS messages yet.");}catch(Exception e){b.append(r.body);}display=b.toString();}else display="Messages unavailable · "+friendly(r);String f=display;ui.post(()->view.setText(f));});}

    private void showObserve(LinearLayout p){p.addView(text("Observe",30,true),mw());p.addView(text("11-core topology · 7 specialists → 2 hemispheres → Consensus → Interface\nStable snapshot only: this screen does not rapid-refresh or reset your scroll.",15,false),mw());TextView snapshot=text("Loading core snapshot…",14,false);ScrollView s=new ScrollView(this);s.addView(snapshot,mw());p.addView(s,new LinearLayout.LayoutParams(-1,0,1));Button refresh=button("Refresh core snapshot");p.addView(refresh,mw());refresh.setOnClickListener(v->loadObserve(snapshot));loadObserve(snapshot);}
    private void loadObserve(TextView view){io.execute(()->{String path="/desktop/runtime-cores"+(profile.isBlank()?"":"?username="+enc(profile));HttpResult r=request("GET",path,null,true);String display;if(r.ok()){try{JSONObject j=new JSONObject(r.body),rt=j.optJSONObject("runtime");StringBuilder b=new StringBuilder();b.append(j.optString("architecture","11-core")).append("\n\n");if(rt!=null){b.append("Phase: ").append(rt.optString("phase","unknown")).append("\nCore count: ").append(rt.opt("core_count")).append("\nServer runtime: ").append(rt.optBoolean("server_runtime_thread_alive",false)?"active":"dormant").append("\nRemote clients: ").append(rt.optInt("remote_clients",0)).append("\nPresence: ").append(rt.optString("presence_state","unknown")).append("\nBackground API budget used: ").append(rt.opt("external_api_budget_used"));}b.append("\n\nCore cycles are deterministic/zero-API unless an explicitly governed external task is used. This is telemetry, not private chain-of-thought.");display=b.toString();}catch(Exception e){display=r.body;}}else display="Observe unavailable · "+friendly(r);String f=display;ui.post(()->view.setText(f));});}

    private void showOptions(LinearLayout p){p.addView(text("Options & System Status",30,true),mw());p.addView(text("Account: "+(profile.isBlank()?"unknown":profile)+"\nServer: "+BuildConfig.SERVER_BASE_URL,14,false),mw());TextView system=text("System status not checked yet.",15,false);p.addView(system,mw());Button check=button("Check system status"),cap=button("Check compatibility"),retry=button("Retry queued messages now"),logout=button("Sign out");p.addView(check,mw());p.addView(cap,mw());p.addView(retry,mw());p.addView(logout,mw());check.setOnClickListener(v->loadSystemStatus(system));cap.setOnClickListener(v->checkCapabilities());retry.setOnClickListener(v->flushSoon(0));logout.setOnClickListener(v->{clearSession();showAuth();});loadSystemStatus(system);}
    private void loadSystemStatus(TextView view){io.execute(()->{HttpResult r=request("GET","/diagnostics/runtime-health",null,false);String display;if(r.ok()){try{JSONObject j=new JSONObject(r.body);boolean main=j.optBoolean("main_app_loaded",false),db=j.optBoolean("database_ok",false),schema=j.optBoolean("auth_schema_ok",false),persist=j.optBoolean("core_persistence_ok",false);String level=main&&db&&schema&&persist?"Healthy":main?"Reduced capability":"Needs attention";display=level+"\n\nServer: "+(main?"online":"degraded bootstrap")+"\nDatabase: "+(db?"healthy":"needs attention")+"\nAuthentication schema: "+(schema?"healthy":"needs attention")+"\nCore persistence: "+(persist?"healthy":"needs attention")+"\nCore phase: "+j.optString("core_phase","unknown")+"\nCore count: "+j.opt("core_count")+"\nFile grounding: "+(j.optBoolean("file_chat_grounding_enabled",false)?"available":"reduced")+"\nImage generation: "+(j.optBoolean("lightweight_image_generation_enabled",false)?"available":"unavailable")+"\nMaintenance review: "+(j.optBoolean("quarterly_maintenance_review_enabled",false)?"available":"unavailable");}catch(Exception e){display="Reduced capability · health response unreadable";}}else display="Needs attention · "+friendly(r);String f=display;ui.post(()->view.setText(f));});}

    private void checkHealth(){io.execute(()->{HttpResult r=request("GET","/health",null,false);ui.post(()->status.setText(r.ok()?"JANUS server reachable":"JANUS server unavailable · "+friendly(r)));});}
    private void checkCapabilities(){io.execute(()->{HttpResult r=request("GET","/protocol/capabilities",null,false);ui.post(()->{if(r.ok())status.setText("Interface active · compatibility received");else{status.setText("Interface active · optional capability negotiation unavailable");checkHealth();}});});}
    private HttpResult request(String method,String path,@Nullable String body,boolean auth){HttpURLConnection c=null;try{c=(HttpURLConnection)new URL(BuildConfig.SERVER_BASE_URL+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(12000);c.setReadTimeout(60000);c.setRequestProperty("Accept","application/json");c.setRequestProperty("Connection","close");if(auth&&!accessToken.isBlank())c.setRequestProperty("Authorization","Bearer "+accessToken);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");try(OutputStream o=c.getOutputStream()){o.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream s=code>=200&&code<400?c.getInputStream():c.getErrorStream();return new HttpResult(code,read(s),null);}catch(Exception e){return new HttpResult(0,"",e.getClass().getSimpleName()+": "+e.getMessage());}finally{if(c!=null)c.disconnect();}}
    private static String read(@Nullable InputStream s)throws Exception{if(s==null)return"";StringBuilder b=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(s,StandardCharsets.UTF_8))){String line;while((line=r.readLine())!=null)b.append(line).append('\n');}return b.toString().trim();}
    private String friendly(HttpResult r){if(r.error!=null&&!r.error.isBlank())return r.error;if(r.code==401)return"Authentication required or session expired.";if(r.code==413)return"File is too large.";if(r.code==415)return"File type is not supported.";if(r.code==429)return"JANUS is rate-limited. Try again shortly.";if(r.code==502||r.code==503||r.code==504)return"JANUS server temporarily unavailable (HTTP "+r.code+").";if(r.code>0)return"HTTP "+r.code+(r.body.isBlank()?"":" · "+r.body);return"Network request failed.";}
    private String enc(String s){return URLEncoder.encode(s,StandardCharsets.UTF_8);}
    private TextView text(String v,int sp,boolean bold){TextView t=new TextView(this);t.setText(v);t.setTextSize(sp);t.setPadding(dp(4),dp(8),dp(4),dp(8));if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;} private EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setSingleLine(true);e.setPadding(dp(12),dp(10),dp(12),dp(10));return e;} private Button button(String l){Button b=new Button(this);b.setText(l);b.setAllCaps(false);return b;} private void toast(String m){Toast.makeText(this,m,Toast.LENGTH_SHORT).show();} private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} private LinearLayout.LayoutParams mw(){return new LinearLayout.LayoutParams(-1,-2);} private LinearLayout.LayoutParams ww(){return new LinearLayout.LayoutParams(-2,-2);}
    private record HttpResult(int code,String body,String error){boolean ok(){return code>=200&&code<300;}} private record Attachment(String id,String name,String mime,long size,String extraction){} private record Q(String id,String message,int attempts,long created,List<Attachment> attachments){String attachmentSignature(){StringBuilder b=new StringBuilder();for(Attachment a:attachments)b.append(a.id).append('|');return b.toString();}} private static final class FileTooLarge extends Exception{}
}
