plugins { id 'com.android.application' }

android {
    namespace 'com.vardath.janus'
    compileSdk 36

    defaultConfig {
        applicationId 'com.vardath.janus'
        minSdk 26
        targetSdk 36
        versionCode 21
        versionName '0.21'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.8.2'
    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.work:work-runtime:2.9.1'
}
